### ISSUE TITLE
mustachify.me down - Application Error

### ISSUE THREAD

**Issue by djdefi** [afeld/mustachio#32]
Unable to mustachify things :(

**Comment by rockerhieu** [comment]
It is down again.

**Comment by zakyg** [comment]
still down

**Comment by Braunson** [comment]
No mustaches for anyone.. still down :( Why does it keep going down?

**Comment by zakyg** [comment]
My bet would be that the service is hitting some Rekognition quota limit...

**Comment by clarkwinkelmann** [comment]
Same here. I have set up Hubot in my company chat but cannot mustach anything :sob: (Nothing critical, but would have been a nice feature)

The homepage works but all the urls with `?src=` return a CloudFlare 502 "Bad gateway" error. It looks like the site is down but the homepage is still in the cache.

I already found a few tweets complaining about it and now I see this thread. I believe that @afeld is the person that can give us some information ?

**Comment by zakyg** [comment]
I think Rekognition are taking their API down, btw, so mustachify would need another solution for it anyway...

**Comment by scarolan** [comment]
Same here.  502 errors for all images that we try.

**Comment by afeld** [comment]
Down until further notice, unfortunately. See https://github.com/afeld/mustachio/issues/48.
